tasks:
  - init: |
      sudo apt-get update
      sudo apt-get install -y util-linux libncurses5-dev libncursesw5-dev gcc g++ binutils bzip2 \
        flex python3 perl make grep diffutils unzip gawk subversion libz-dev libc-dev rsync
      exit
  - command: |
      git clone https://github.com/jjm2473/rtd129x-uboot.git rtd129x-uboot
      wget https://github.com/jjm2473/rtd1296_prebuilt_target/releases/download/v1.0/rtk-uboot-binary_1.tar.gz
      tar -xz rtk-uboot-binary_1.tar.gz -C rtd129x-uboot
      wget https://releases.linaro.org/components/toolchain/binaries/7.3-2018.05/aarch64-linux-gnu/gcc-linaro-7.3.1-2018.05-x86_64_aarch64-linux-gnu.tar.xz 
      mkdir linux-gnu && tar -xf gcc-linaro-7.3.1-2018.05-x86_64_aarch64-linux-gnu.tar.xz -C linux-gnu
      export PATH=$PATH:/workspace/istoreos-rtd129x-build/linux-gnu/bin
      wget https://github.com/jjm2473/rtd1296_prebuilt_target/releases/download/v1.0/rtd129x_img_tools-linux_x86_64.tar.gz
      mkdir img_tools && tar rtd129x_img_tools-linux_x86_64.tar.gz -xz -C img_tools
      export PATH=$PATH:/workspace/istoreos-rtd129x-build/img_tools
      cd rtd129x-uboot
      make CROSS_COMPILE="aarch64-linux-gnu-" rtd1296_qa_NAS_config
      make CROSS_COMPILE="aarch64-linux-gnu-" V=s
      mkdir old
      mv ../*.bin ./old
      mkdir new
      
