tasks:
  - init: |
      sudo apt-get update
      sudo apt-get install -y util-linux libncurses5-dev libncursesw5-dev gcc g++ binutils bzip2 \
        flex python3 perl make grep diffutils unzip gawk subversion libz-dev libc-dev rsync
      exit
  - command: |
      git clone -b istoreos-21.02  https://github.com/istoreos/istoreos
      cp config.txt istoreos/.config
      cd istoreos
      ./scripts/feeds update -a
      ./scripts/feeds install -a
      make menuconfig && make -j$(nproc) PKG_HASH=skip || (cd ../; bash fix.sh)
