tasks:
  - init: |
      sudo apt-get update
      sudo apt-get install -y util-linux libncurses5-dev libncursesw5-dev gcc g++ binutils bzip2 \
        flex python3 perl make grep diffutils unzip gawk subversion libz-dev libc-dev rsync
      exit
  - command: |
      git clone https://github.com/houandy/rtd129x-uboot.git rtd129x-uboot
      wget https://github.com/jjm2473/rtd1296_prebuilt_target/releases/download/v1.0/rtk-uboot-binary_1.tar.gz
      tar -xzf rtk-uboot-binary_1.tar.gz -C rtd129x-uboot
      wget https://releases.linaro.org/components/toolchain/binaries/7.3-2018.05/aarch64-linux-gnu/gcc-linaro-7.3.1-2018.05-x86_64_aarch64-linux-gnu.tar.xz 
      tar -xf gcc-linaro-7.3.1-2018.05-x86_64_aarch64-linux-gnu.tar.xz
      mv gcc-linaro-7.3.1-2018.05-x86_64_aarch64-linux-gnu linux-gnu
      export PATH=$PATH:/workspace/istoreos-rtd129x-build/linux-gnu/bin
      wget https://github.com/jjm2473/rtd1296_prebuilt_target/releases/download/v1.0/rtd129x_img_tools-linux_x86_64.tar.gz
      mkdir img_tools && tar -xzf rtd129x_img_tools-linux_x86_64.tar.gz -C img_tools
      export PATH=$PATH:/workspace/istoreos-rtd129x-build/img_tools
      cd rtd129x-uboot
      make CROSS_COMPILE="aarch64-linux-gnu-" rtd1296_emmc_bananapi_defconfig
      make CROSS_COMPILE="aarch64-linux-gnu-" V=s
      mkdir old
      mv ../*.bin ./old
      cp -Rf ../129* ./
      mkdir new new5 new6
      rtd129x_bootcode_gen -d new -h old/hw_setting.bin -u u-boot.bin -f old/fsbl.bin
      rtd129x_bootcode_gen -d new5 -h 1295/hw_setting.bin -u u-boot.bin -f 1295/fsbl.bin
      rtd129x_bootcode_gen -d new6 -h 1296/hw_setting.bin -u u-boot.bin -f 1296/fsbl.bin
      sh -c 'cd new; tar -cf ../bootloader.tar *'
      sh -c 'cd new5; tar -cf ../1295/bootloader.tar *'
      sh -c 'cd new6; tar -cf ../1296/bootloader.tar *'
